In [2]:
import pandas as pd
from IPython.display import display, Markdown
import ast
#from camel_tools.utils.dediac import dediac_ar
from IPython.display import display,Markdown
#from llama_index.core.node_parser import SemanticSplitterNodeParser
#from llama_index.embeddings.huggingface import HuggingFaceEmbedding
#from llama_index.core import Document
from bs4 import BeautifulSoup as bs
from tqdm import tqdm
import numpy as np

# Make db

In [2]:
df = pd.read_csv('shameladb_books.csv')
df = df[df['is_downloaded']]
df = df.dropna(subset=['content'])
df.head()

,book_id,book_name,book_category,book_type,book_date,authors,main_author,printed,group_id,hidden,...,book_up,category_name,main_author_name,main_author_death,all_authors,coauthors,is_downloaded,content,page_count,headers
114,121,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,1,1,280,1198,1198,1,NaN,0,...,NaN,العقيدة,حرب الكرماني,280,حرب الكرماني,NaN,True,"[{""page_id"": ""121-1"", ""body"": """", ""header"": """"...",225,"[""تقديم فضيلة الشيخ الدكتور/ محمد بن هادي المد..."
160,170,الجواب الصحيح لمن بدل دين المسيح لابن تيمية,1,1,728,54,54,1,NaN,0,...,NaN,العقيدة,ابن تيمية,728,ابن تيمية,NaN,True,"[{""page_id"": ""170-1"", ""body"": ""<span data-type...",3059,"[""مقدمة الكتاب"", ""فصل: دين الأنبياء واحد هو ال..."
249,264,تحقيق الإيمان لابن تيمية,1,1,728,54,54,1,NaN,0,...,NaN,العقيدة,ابن تيمية,728,ابن تيمية,NaN,True,"[{""page_id"": ""264-1"", ""body"": ""<span data-type...",168,"[""الإيمان لابن تيمية""]"
282,301,تحقيق الاحتجاج بالقدر لابن تيمية,1,1,728,54,54,1,NaN,0,...,NaN,العقيدة,ابن تيمية,728,ابن تيمية,NaN,True,"[{""page_id"": ""301-1"", ""body"": ""<span data-type...",28,"[""الاحتجاج بالقدر""]"
302,323,السنة لعبد الله بن أحمد,1,1,290,309,309,1,NaN,0,...,NaN,العقيدة,عبد الله بن أحمد,290,عبد الله بن أحمد,NaN,True,"[{""page_id"": ""323-1"", ""body"": ""أَحْمَدُ اللَّه...",1516,"[""عبد الله بن المبارك رحمه الله"", ""سفيان بن عي..."

In [3]:
df = df[['book_id','book_category','book_type','book_date','book_name','category_name','all_authors','meta_data','is_downloaded','content','page_count']]

In [4]:
df['content'] = df['content'].apply(ast.literal_eval)
df = df.explode('content').reset_index(drop=True)
df.head()

,book_id,book_category,book_type,book_date,book_name,category_name,all_authors,meta_data,is_downloaded,content,page_count
0,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-1', 'body': '', 'header': '',...",225
1,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-2', 'body': '', 'header': '',...",225
2,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-3', 'body': '', 'header': '',...",225
3,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-4', 'body': '', 'header': 'تق...",225
4,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-5', 'body': '', 'header': 'تق...",225

In [ ]:
def adding_page_tobody(row):
    row['body'] = f"{row.body} <page>{row.page}</page>"   
    return row

In [6]:
df['headers'] = df['content'].apply(lambda x: x['headers'])
df['page'] = df['content'].apply(lambda x: int(x['page_id'].split('-')[-1]))
df['body'] = df['content'].apply(lambda x: str(x['body']))
df = df[df['body'] != '']
df = df.apply(adding_page_tobody,axis=1)

In [7]:
df.head()

,book_id,book_category,book_type,book_date,book_name,category_name,all_authors,meta_data,is_downloaded,content,page_count,headers,page,body
22,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-23', 'body': '<span data-type...",225,[باب القول بالمذهب],23,"<span data-type=""title"" id=toc-12>باب القول با..."
23,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-24', 'body': 'والحجاز والشام ...",225,[باب القول بالمذهب],24,والحجاز والشام وغيرهم [عليها] (¬١)، فمن خالف ش...
24,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-25', 'body': 'وأخذنا عنهم الع...",225,[من زعم أن الإيمان قول بلا عمل],25,وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...
25,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-26', 'body': '* ومن زعم أن ال...",225,[من زعم أن الإيمان يزيد ولا ينقص],26,* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...
26,121,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"{""date"": ""02041442""}",True,"{'page_id': '121-27', 'body': '. . . . . . . ....",225,[من زعم أن الإيمان يزيد ولا ينقص],27,. . . . . . . . . . . . . . . . . . . . . . . ...

In [8]:

def get_html(row):
    soup = bs(row.body,'html.parser')
    spans = soup.find_all(attrs={"data-type": "title"})
    if len(spans) == 0:
        return row
    headers = row.headers
    for i,span in enumerate(spans):
        body = ''
        for sp in span.contents:
            if isinstance(sp,str):
                body += f"{sp} "
            else:
                body += f"{sp.contents[0]}"
        try:                                                                                             
            idx = headers.index(str(body))                                                     
            depth = idx + 1  # 1 → '#', 2 → '##', etc.                                                   
        except ValueError:                                                                               
            depth = len(headers)  # fallback  
        markdown = '#' * depth + ' ' + body + '\n'                                                  
        span.replace_with(markdown)
    row['body'] = str(soup)                                                                            
    return row   

tqdm.pandas()
df = df.progress_apply(get_html,axis=1)

100%|██████████| 102253/102253 [00:38<00:00, 2667.24it/s]

In [9]:
df['headers_tree'] = df['headers'].apply(lambda x: "/".join(x))

In [10]:
# Group consecutive rows with same headers
# Convert headers from string → tuple for grouping
df["headers_tuple"] = df["headers"].apply(lambda x: tuple(eval(x)) if isinstance(x, str) else tuple(x))

# Mark consecutive groups
df["_group"] = (df["headers_tuple"] != df["headers_tuple"].shift()).cumsum()

# Aggregate
grouped = df.groupby(["_group", "book_id", "headers_tuple"], as_index=False).agg(
    book_category=('book_category',list),
    book_type=('book_type',list),
    book_date=('book_date',list),
    book_name=('book_name',list),
    category_name=('category_name',list),
    all_authors=('all_authors',list),
    body=("body", lambda texts: "\n".join(texts)),
    pages=("page", list),
    page_count=("page", "count"),
)

# Drop temp columns from original if desired
df.drop(columns=["headers_tuple", "_group"], inplace=True)

# Preview
grouped.head()

,_group,book_id,headers_tuple,book_category,book_type,book_date,book_name,category_name,all_authors,body,pages,page_count
0,1,121,"(باب القول بالمذهب,)","[1, 1]","[1, 1]","[280, 280]",[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني...,"[العقيدة, العقيدة]","[حرب الكرماني, حرب الكرماني]",# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,"[23, 24]",2
1,2,121,"(من زعم أن الإيمان قول بلا عمل,)",[1],[1],[280],[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني],[العقيدة],[حرب الكرماني],وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,[25],1
2,3,121,"(من زعم أن الإيمان يزيد ولا ينقص,)","[1, 1]","[1, 1]","[280, 280]",[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني...,"[العقيدة, العقيدة]","[حرب الكرماني, حرب الكرماني]",* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,"[26, 27]",2
3,4,121,"(من زعم أن الناس لا يتفاضلون في الإيمان فقد كذب,)",[1],[1],[280],[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني],[العقيدة],[حرب الكرماني],* و# من لم ير الاستثناء في الإيمان \n؛ فهو مرج...,[28],1
4,5,121,"(القدر خيره وشره من الله,)",[1],[1],[280],[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني],[العقيدة],[حرب الكرماني],* ومن زعم أن المعرفة تنفع (¬١) في القلب وإن لم...,[29],1

In [11]:
grouped['book_type'] = grouped['book_type'].apply(lambda x: x[0])
grouped['book_category'] = grouped['book_category'].apply(lambda x: x[0])
grouped['book_date'] = grouped['book_date'].apply(lambda x: x[0])
grouped['book_name'] = grouped['book_name'].apply(lambda x: x[0])
grouped['category_name'] = grouped['category_name'].apply(lambda x: x[0])
grouped['all_authors'] = grouped['all_authors'].apply(lambda x: x[0])

In [16]:
grouped['headers_tuple'] = grouped['headers_tuple'].apply(lambda x: "/".join(list(x)))

In [20]:
grouped.to_csv('shameladb_books_enh.csv')

# Chunker

In [2]:
df = pd.read_csv('shameladb_books_enh.csv')

In [3]:
embed_model = HuggingFaceEmbedding('models/gate_arabert_onnx/',backend="onnx",
    model_kwargs={"file_name": "model_int8.onnx"})

splitter = SemanticSplitterNodeParser(
    buffer_size=2, # Contextual buffer (number of sentences) around split points
    breakpoint_percentile_threshold=75, # Sensitivity to semantic shifts
    embed_model=embed_model
)
splitter = SemanticSplitterNodeParser(
    buffer_size=2, # Contextual buffer (number of sentences) around split points
    breakpoint_percentile_threshold=75, # Sensitivity to semantic shifts
    embed_model=embed_model
)

In [4]:
def gen_chunks(text):
    doc = Document(id=1,text=text)
    chunks = splitter([doc])
    return [chunk.text for chunk in chunks]

In [ ]:
from tqdm import tqdm
tqdm.pandas()

In [ ]:
df['chunks'] = df['body'].progress_apply(gen_chunks)

  0%|          | 0/366 [00:00<?, ?it/s]

 32%|███▏      | 116/366 [1:25:44<3:04:47, 44.35s/it]

KeyboardInterrupt:

# chunks

In [41]:
df = pd.read_csv('asdf.csv')
df['chunks'] = df['chunks'].apply(ast.literal_eval)

In [42]:
df = df.drop(columns=['body', 'Unnamed: 0.1', 'Unnamed: 0'])

In [43]:
def optimize_int_columns(df):
    optimized_df = df.copy()
    for col in optimized_df.select_dtypes(include=['int64']).columns:
        min_val = optimized_df[col].min()
        max_val = optimized_df[col].max()

        if min_val >= 0:
            if max_val < 255: # uint8
                optimized_df[col] = optimized_df[col].astype('uint8')
            elif max_val < 65535: # uint16
                optimized_df[col] = optimized_df[col].astype('uint16')
            elif max_val < 4294967295: # uint32
                optimized_df[col] = optimized_df[col].astype('uint32')
        else:
            if min_val > -128 and max_val < 127: # int8
                optimized_df[col] = optimized_df[col].astype('int8')
            elif min_val > -32768 and max_val < 32767: # int16
                optimized_df[col] = optimized_df[col].astype('int16')
            elif min_val > -2147483648 and max_val < 2147483647: # int32
                optimized_df[col] = optimized_df[col].astype('int32')
    return optimized_df

# Apply integer optimization
df = optimize_int_columns(df)

In [74]:
df.info()

<class 'pandas.DataFrame'>
Index: 99771 entries, 0 to 23569
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _group         99771 non-null  uint16
 1   book_id        99771 non-null  uint32
 2   headers_tuple  99623 non-null  category
 3   book_category  99771 non-null  uint8
 4   book_type      99771 non-null  uint8
 5   book_date      99771 non-null  uint16
 6   book_name      99771 non-null  category
 7   category_name  99771 non-null  category
 8   all_authors    99771 non-null  category
 9   pages          99771 non-null  object
 10  page_count     99771 non-null  uint16
 11  chunks         99771 non-null  category
 12  chunk_page     99771 non-null  object
dtypes: category(5), object(2), uint16(3), uint32(1), uint8(2)
memory usage: 109.5+ MB

In [46]:
df['pages'] = df['pages'].apply(lambda x: x if pd.isna(x) else ast.literal_eval(x))

In [49]:
df = df.explode('chunks')

In [51]:
chunk_pages = []
for row in df.itertuples():
    chunk = row.chunks
    soup = bs(chunk,'html.parser')
    spans_found = soup.find_all('page')
    if spans_found:
        page = spans_found[-1].contents[-1]
        spans_str = [int(span.contents[0]) for span in spans_found]
        if not spans_str:
            spans_str = f"{page}, {int(page)+1}"
    else:
        spans_str = [int(page) for page in row.pages] # Handle cases where no 'page' tags are found
    chunk_pages.append(spans_str)
df['chunk_page'] = chunk_pages

In [64]:
df.info()

<class 'pandas.DataFrame'>
Index: 99771 entries, 0 to 23569
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   _group         99771 non-null  uint16
 1   book_id        99771 non-null  uint32
 2   headers_tuple  99623 non-null  category
 3   book_category  99771 non-null  uint8
 4   book_type      99771 non-null  uint8
 5   book_date      99771 non-null  uint16
 6   book_name      99771 non-null  category
 7   category_name  99771 non-null  category
 8   all_authors    99771 non-null  category
 9   pages          99771 non-null  object
 10  page_count     99771 non-null  uint16
 11  chunks         99771 non-null  category
 12  chunk_page     99771 non-null  object
dtypes: category(5), object(2), uint16(3), uint32(1), uint8(2)
memory usage: 109.5+ MB

In [63]:
def optimize_object_columns(df):
    optimized_df = df.copy()
    for col in optimized_df.select_dtypes(include=['object']).columns:
        optimized_df[col] = optimized_df[col].astype('category',errors='ignore')
    return optimized_df

# Apply object optimization
df = optimize_object_columns(df)

In [34]:
df.head()

,_group,book_id,headers_tuple,book_category,book_type,book_date,book_name,category_name,all_authors,pages,page_count,chunks,chunk_page
0,1,121,باب القول بالمذهب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"[23, 24]",2,# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,"[23, 24]"
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,[25]
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,* و# من زعم أن الإيمان قول بلا عمل \n؛ فهو مرج...,[25]
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,<page>25</page>,[25]
2,3,121,من زعم أن الإيمان يزيد ولا ينقص,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"[26, 27]",2,* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,"[26, 27]"

In [ ]:
from datasets import Dataset
from huggingface_hub import login

dataset = Dataset.from_pandas(df)

# Push to your repository
dataset.to_parquet('data/full_book')

Creating parquet from Arrow format: 100%|██████████| 8/8 [00:03<00:00,  2.09ba/s]

765856919

# Updates

In [3]:
from datasets import load_dataset

ds = load_dataset('SHK4K/islam_books')
df = ds['train'].to_pandas()
df.head()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")

README.md:   0%|          | 0.00/886 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/train-00000-of-00002.parquet: reconstructing file:   0%|          |  0.00B / 28.1MB

data/train-00000-of-00002.parquet: downloading bytes:           |  0.00B

data/train-00001-of-00002.parquet: reconstructing file:   0%|          |  0.00B / 20.7MB

data/train-00001-of-00002.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/99771 [00:00<?, ? examples/s]

,_group,book_id,headers_tuple,book_category,book_type,book_date,book_name,category_name,all_authors,pages,page_count,chunks,chunk_page,__index_level_0__
0,1,121,باب القول بالمذهب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"[23, 24]",2,# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,"23, 24",0
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,25,1
2,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,* و# من زعم أن الإيمان قول بلا عمل \n؛ فهو مرج...,25,1
3,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,<page>25</page>,25,1
4,3,121,من زعم أن الإيمان يزيد ولا ينقص,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"[26, 27]",2,* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,"26, 27",2

In [4]:
chunk_pages = []
page = 1
for row in df.itertuples():
    chunk = row.chunks
    soup = bs(chunk,'html.parser')
    spans_found = soup.find_all('page')
    if spans_found:
        page = spans_found[-1].contents[-1]
        spans_str = ", ".join([span.contents[0] for span in spans_found])
        
    else:
        spans_str = f'{page}, {int(page)+1}' # Handle cases where no 'page' tags are found
    chunk_pages.append(spans_str)
df['chunk_page'] = chunk_pages

In [5]:
from datasets import Dataset
dataset = Dataset.from_pandas(df)

# Push to your repository
dataset.push_to_hub("SHK4K/islam_books",token='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')

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/100 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :  47%|####6     | 22.8MB / 48.5MB

CommitInfo(commit_url='https://huggingface.co/datasets/SHK4K/islam_books/commit/51e5ec615480d34bfbefe7cdf0d30f977d7deffa', commit_message='Upload dataset', commit_description='', oid='51e5ec615480d34bfbefe7cdf0d30f977d7deffa', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/SHK4K/islam_books', endpoint='https://huggingface.co', repo_type='dataset', repo_id='SHK4K/islam_books'), pr_revision=None, pr_num=None)