In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!pip install --upgrade pip setuptools wheel
!pip install camel_tools

Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Downloading pip-26.2-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (75.2.0)
Collecting setuptools
  Downloading setuptools-83.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: wheel in /usr/local/lib/python3.12/dist-packages (0.47.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from wheel) (26.2)
Downloading pip-26.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 21.7 MB/s eta 0:00:0000:010:01
Downloading setuptools-83.0.0-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 54.3 MB/s eta 0:00:00
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
torch 2.11.0+cpu requires setuptools<82, but you have setuptools 83.0.0 which is incompatible.
Successfully installed pip-26.2 setuptools-83.0.0

Collecting camel_tools
  Downloading camel_tools-1.6.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: cachetools>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from camel_tools) (6.2.6)
Collecting camel-kenlm>=2026.02.07 (from camel_tools)
  Downloading camel_kenlm-2026.2.7-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (250 bytes)
Collecting dill>=0.4.0 (from camel_tools)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting docopt (from camel_tools)
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: editdistance in /usr/local/lib/python3.12/dist-packages (from camel_tools) (0.8.1)
Collecting emoji (from camel_tools)
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: future in /usr/local/lib/python3.12/dist-packages (from camel_tools) (1.0.0)
Collecting muddler (from camel_tools)
  Downloading muddler-0.1.3-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from camel_tools) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from camel_tools) (2.2.2)
Collecting pyrsistent (from camel_tools)
  Downloading pyrsistent-0.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from camel_tools) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from camel_tools) (2.32.4)
Collecting scikit-learn>=1.8.0 (from camel_tools)
  Downloading scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from camel_tools) (1.16.3)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from camel_tools) (1.17.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from camel_tools) (0.9.0)
Requirement already satisfied: torch>=2.0 in /usr/local/lib/python3.12/dist-packages (from camel_tools) (2.11.0+cpu)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from camel_tools) (4.67.3)
Requirement already satisfied: transformers>=4.44.0 in /usr/local/lib/python3.12/dist-packages (from camel_tools) (5.13.1)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.8.0->camel_tools) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.8.0->camel_tools) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.8.0->camel_tools) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->camel_tools) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->camel_tools) (4.16.0)
Collecting setuptools<82 (from torch>=2.0->camel_tools)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->camel_tools) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->camel_tools) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->camel_tools) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0->camel_tools) (2025.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0->camel_tools) (1.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.44.0->camel_tools) (1.23.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.44.0->camel_tools) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.44.0->camel_tools) (6.0.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.44.0->camel_tools) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.44.0->camel_tools) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.44.0->camel_tools) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.44.0->camel_tools) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.44.0->camel_tools) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.44.0->camel_tools) (0.28.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.44.0->camel_tools) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.44.0->camel_tools) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.44.0->camel_tools) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.44.0->camel_tools) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.44.0->camel_tools) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0->camel_tools) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->camel_tools) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->camel_tools) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->camel_tools) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->camel_tools) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->camel_tools) (2.5.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.44.0->camel_tools) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.44.0->camel_tools) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.44.0->camel_tools) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.44.0->camel_tools) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.44.0->camel_tools) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.44.0->camel_tools) (0.1.2)
Downloading camel_tools-1.6.0-py3-none-any.whl (125 kB)
Downloading camel_kenlm-2026.2.7-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 48.1 MB/s  0:00:00
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 127.0 MB/s  0:00:00
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 46.7 MB/s  0:00:00
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 27.1 MB/s  0:00:00
Downloading muddler-0.1.3-py3-none-any.whl (16 kB)
Downloading pyrsistent-0.20.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (122 kB)
Building wheels for collected packages: docopt
  Building wheel for docopt (pyproject.toml) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13782 sha256=9a78ed86825757ec3f2828224f3a0299824a6d9d30343c40abdf607a74dbfc6a
  Stored in directory: /root/.cache/pip/wheels/1a/bf/a1/4cee4f7678c68c5875ca89eaccf460593539805c3906722228
Successfully built docopt
Installing collected packages: docopt, camel-kenlm, setuptools, pyrsistent, muddler, emoji, dill, scikit-learn, camel_tools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 83.0.0
    Uninstalling setuptools-83.0.0:
      Successfully uninstalled setuptools-83.0.0━━━━━━━━━━━━━━━━━━ 2/9 [setuptools]
  Attempting uninstall: dill0m╺━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/9 [pyrsistent]
    Found existing installation: dill 0.3.8━━━━━━━━━━━━━━━━━━━ 3/9 [pyrsistent]
    Uninstalling dill-0.3.8:[0m━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/9 [pyrsistent]
      Successfully uninstalled dill-0.3.8━━━━━━━━━━━━━━━━━━━━━ 3/9 [pyrsistent]
  Attempting uninstall: scikit-learn0m╸━━━━━━━━━━━━━ 6/9 [dill]t]
    Found existing installation: scikit-learn 1.6.1━━━━━━━━━━━ 6/9 [dill]
    Uninstalling scikit-learn-1.6.1:91m╸━━━━━━━━━━━━━ 6/9 [dill]
      Successfully uninstalled scikit-learn-1.6.1━━━━━━━━ 7/9 [scikit-learn]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [camel_tools] [scikit-learn]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
datasets 4.0.0 requires dill<0.3.9,>=0.3.0, but you have dill 0.4.1 which is incompatible.
Successfully installed camel-kenlm-2026.2.7 camel_tools-1.6.0 dill-0.4.1 docopt-0.6.2 emoji-2.15.0 muddler-0.1.3 pyrsistent-0.20.0 scikit-learn-1.9.0 setuptools-81.0.0

In [3]:
!pip install llama_index llama-index-embeddings-huggingface

Collecting llama_index
  Downloading llama_index-0.14.23-py3-none-any.whl.metadata (14 kB)
Collecting llama-index-embeddings-huggingface
  Downloading llama_index_embeddings_huggingface-0.7.0-py3-none-any.whl.metadata (459 bytes)
Collecting llama-index-core<0.15.0,>=0.14.23 (from llama_index)
  Downloading llama_index_core-0.14.23-py3-none-any.whl.metadata (2.6 kB)
Collecting llama-index-embeddings-openai<0.7,>=0.6.0 (from llama_index)
  Downloading llama_index_embeddings_openai-0.6.0-py3-none-any.whl.metadata (401 bytes)
Collecting llama-index-llms-openai<0.8,>=0.7.0 (from llama_index)
  Downloading llama_index_llms_openai-0.7.10-py3-none-any.whl.metadata (3.0 kB)
Collecting nltk>=3.9.3 (from llama_index)
  Downloading nltk-3.10.1-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (3.14.1)
Requirement already satisfied: aiosqlite in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (0.22.1)
Collecting banks<3,>=2.3.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading banks-2.4.5-py3-none-any.whl.metadata (12 kB)
Collecting dataclasses-json (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting deprecated>=1.2.9.3 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting dirtyjson<2,>=1.0.8 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting filetype<2,>=1.2.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2025.3.0)
Requirement already satisfied: httpx in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (0.28.1)
Collecting llama-index-workflows<3,>=2.14.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading llama_index_workflows-2.22.2-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2.0.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (11.3.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (4.10.0)
Requirement already satisfied: pydantic>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2.13.4)
Requirement already satisfied: pyyaml>=6.0.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2.32.4)
Requirement already satisfied: setuptools>=80.9.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (81.0.0)
Requirement already satisfied: sqlalchemy>=1.4.49 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.23->llama_index) (2.0.51)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (9.1.4)
Requirement already satisfied: tiktoken>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (0.13.0)
Collecting tinytag>=2.2.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading tinytag-2.3.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: tqdm<5,>=4.66.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (4.67.3)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (4.16.0)
Collecting typing-inspect>=0.8.0 (from llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from llama-index-core<0.15.0,>=0.14.23->llama_index) (2.2.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4,>=3.8.6->llama-index-core<0.15.0,>=0.14.23->llama_index) (1.24.2)
Collecting griffe (from banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading griffe-2.1.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (3.1.6)
Requirement already satisfied: openai>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (2.45.0)
Collecting llama-index-instrumentation>=0.4.3 (from llama-index-workflows<3,>=2.14.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading llama_index_instrumentation-0.5.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (4.14.2)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (0.16.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (1.3.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai>=1.1.0->llama-index-embeddings-openai<0.7,>=0.6.0->llama_index) (3.18)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.23->llama_index) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx->llama-index-core<0.15.0,>=0.14.23->llama_index) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx->llama-index-core<0.15.0,>=0.14.23->llama_index) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.8.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (0.4.2)
Requirement already satisfied: huggingface-hub>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.23.0)
Requirement already satisfied: sentence-transformers>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from llama-index-embeddings-huggingface) (5.6.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (3.29.7)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (26.2)
WARNING: huggingface-hub 1.23.0 does not provide the extra 'inference'
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (0.7.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9.3->llama_index) (2025.11.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (2.5.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (5.13.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.11.0+cpu)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.9.0)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.16.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.8.0)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (3.6.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.49->sqlalchemy[asyncio]>=1.4.49->llama-index-core<0.15.0,>=0.14.23->llama_index) (3.5.3)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.14.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.3.0)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading mypy_extensions-1.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting griffecli==2.1.0 (from griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading griffecli-2.1.0-py3-none-any.whl.metadata (1.2 kB)
Collecting griffelib==2.1.0 (from griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading griffelib-2.1.0-py3-none-any.whl.metadata (1.3 kB)
Collecting colorama>=0.4 (from griffecli==2.1.0->griffe->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->banks<3,>=2.3.0->llama-index-core<0.15.0,>=0.14.23->llama_index) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers>=2.6.1->llama-index-embeddings-huggingface) (0.1.2)
Downloading llama_index-0.14.23-py3-none-any.whl (7.1 kB)
Downloading llama_index_core-0.14.23-py3-none-any.whl (11.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 85.8 MB/s  0:00:00
Downloading banks-2.4.5-py3-none-any.whl (36 kB)
Downloading dirtyjson-1.0.8-py3-none-any.whl (25 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading llama_index_embeddings_openai-0.6.0-py3-none-any.whl (7.7 kB)
Downloading llama_index_llms_openai-0.7.10-py3-none-any.whl (28 kB)
Downloading llama_index_workflows-2.22.2-py3-none-any.whl (164 kB)
Downloading llama_index_embeddings_huggingface-0.7.0-py3-none-any.whl (8.9 kB)
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading llama_index_instrumentation-0.5.0-py3-none-any.whl (16 kB)
Downloading nltk-3.10.1-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 44.8 MB/s  0:00:00
Downloading tinytag-2.3.0-py3-none-any.whl (37 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading mypy_extensions-1.1.0-py3-none-any.whl (5.0 kB)
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
Downloading griffe-2.1.0-py3-none-any.whl (5.1 kB)
Downloading griffecli-2.1.0-py3-none-any.whl (9.5 kB)
Downloading griffelib-2.1.0-py3-none-any.whl (142 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: filetype, dirtyjson, tinytag, nltk, mypy-extensions, marshmallow, griffelib, deprecated, colorama, typing-inspect, griffecli, llama-index-instrumentation, griffe, dataclasses-json, llama-index-workflows, banks, llama-index-core, llama-index-llms-openai, llama-index-embeddings-openai, llama-index-embeddings-huggingface, llama_index
  Attempting uninstall: nltk
    Found existing installation: nltk 3.9.1
    Uninstalling nltk-3.9.1:
      Successfully uninstalled nltk-3.9.1━━━━━━━━━━━━━━━━━━━━━━━━━  3/21 [nltk]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21/21 [llama_index][0m [llama-index-embeddings-openai]
Successfully installed banks-2.4.5 colorama-0.4.6 dataclasses-json-0.6.7 deprecated-1.3.1 dirtyjson-1.0.8 filetype-1.2.0 griffe-2.1.0 griffecli-2.1.0 griffelib-2.1.0 llama-index-core-0.14.23 llama-index-embeddings-huggingface-0.7.0 llama-index-embeddings-openai-0.6.0 llama-index-instrumentation-0.5.0 llama-index-llms-openai-0.7.10 llama-index-workflows-2.22.2 llama_index-0.14.23 marshmallow-3.26.2 mypy-extensions-1.1.0 nltk-3.10.1 tinytag-2.3.0 typing-inspect-0.9.0

In [121]:
import pandas as pd
from IPython.display import display, Markdown
import ast
from camel_tools.utils.dediac import dediac_ar
from IPython.display import display,Markdown
# from llama_index.core.node_parser import SemanticSplitterNodeParser
# from llama_index.embeddings.huggingface import HuggingFaceEmbedding
# from llama_index.core import Document
from bs4 import BeautifulSoup as bs
from tqdm import tqdm
import numpy as np

In [2]:
tqdm.pandas()

# Make db

In [113]:
!cp -rf drive/MyDrive/data/shameladb_books.csv .

In [114]:
df = pd.read_csv('shameladb_books.csv')
df = df[df['is_downloaded']]
df = df.dropna(subset=['content'])
df.head()

,book_id,book_name,book_category,book_type,book_date,authors,main_author,printed,group_id,hidden,...,book_up,category_name,main_author_name,main_author_death,all_authors,coauthors,is_downloaded,content,page_count,headers
114,121,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,1,1,280,1198,1198,1,NaN,0,...,NaN,العقيدة,حرب الكرماني,280,حرب الكرماني,NaN,True,"[{""page_id"": ""121-1"", ""body"": """", ""header"": """"...",225,"[""تقديم فضيلة الشيخ الدكتور/ محمد بن هادي المد..."
160,170,الجواب الصحيح لمن بدل دين المسيح لابن تيمية,1,1,728,54,54,1,NaN,0,...,NaN,العقيدة,ابن تيمية,728,ابن تيمية,NaN,True,"[{""page_id"": ""170-1"", ""body"": ""<span data-type...",3059,"[""مقدمة الكتاب"", ""فصل: دين الأنبياء واحد هو ال..."
168,178,اتباع السنن واجتناب البدع,1,1,643,603,603,1,NaN,0,...,NaN,العقيدة,ضياء الدين المقدسي,643,ضياء الدين المقدسي,NaN,True,"[{""page_id"": ""178-1"", ""body"": ""<span data-type...",69,"[""بسم الله الرحمن الرحيم وبه نستعين"", ""جزء من ..."
174,184,الصواعق المرسلة على الجهمية والمعطلة - ط عطاءا...,2,1,751,14,14,1,7345.0,0,...,NaN,الفرق والردود,ابن القيم,751,ابن القيم,NaN,True,"[{""page_id"": ""184-1"", ""body"": ""آثار الإمام ابن...",1654,"[""مقدمة المحقق"", ""التعريف بكتاب «الصواعق المرس..."
195,205,شفاء العليل في مسائل القضاء والقدر والحكمة وال...,1,1,751,14,14,1,NaN,0,...,NaN,العقيدة,ابن القيم,751,ابن القيم,NaN,True,"[{""page_id"": ""205-1"", ""body"": """", ""header"": """"...",1617,"[""مقدمة التحقيق"", ""توثيق نسبة الكتاب"", ""عنوان ..."

In [115]:
df = df[['book_id','book_category','book_type','book_date','book_name','category_name','all_authors','main_author_death','content','page_count']]

In [118]:
df['content'] = df['content'].apply(ast.literal_eval)
df = df.explode('content').reset_index(drop=True)

In [10]:
def adding_page_tobody(row):
    row['body'] = f"{row.body} <page>{row.page}</page>"   
    return row

In [119]:
df['headers'] = df['content'].progress_apply(lambda x: x.get('headers',''))
df['header'] = df['content'].progress_apply(lambda x: x.get('header',[]))
df['page'] = df['content'].progress_apply(lambda x: int(x['page_id'].split('-')[-1]))
df['body'] = df['content'].progress_apply(lambda x: str(x['body']))
df = df[df['body'] != '']
# df = df.progress_apply(adding_page_tobody,axis=1)

100%|██████████| 217332/217332 [00:00<00:00, 1134198.51it/s]
100%|██████████| 217332/217332 [00:00<00:00, 990147.45it/s]
100%|██████████| 217332/217332 [00:00<00:00, 648439.73it/s]
100%|██████████| 217332/217332 [00:00<00:00, 876575.84it/s]

In [149]:
from bs4 import BeautifulSoup as bs
from bs4 import NavigableString

def get_html(row):
    soup = bs(row.body, "html.parser")

    spans = soup.find_all(attrs={"data-type": "title"})
    if not spans:
        return row

    headers = row.headers

    for span in spans:
        body = "".join(
            str(c) if isinstance(c, NavigableString) else c.get_text()
            for c in span.contents
        ).strip()

        try:
            idx = headers.index(body)
            depth = idx + 1
        except ValueError:
            depth = len(headers)

        markdown = "#" * depth + " " + body + "\n"
        span.replace_with(NavigableString(markdown))

    # Remove every remaining HTML tag, keeping only their text
    for tag in soup.find_all(True):
        tag.unwrap()

    row["body"] = soup.get_text()
    return row

df = df.progress_apply(get_html,axis=1)

100%|██████████| 216436/216436 [00:46<00:00, 4618.45it/s]

In [150]:
df['headers_tree'] = df['headers'].apply(lambda x: "/".join(x))

In [ ]:
sep = ' '

df["page_len"] = df["body"].str.len() + len(sep)

df["page_end"] = (
    df.groupby(["book_id", "book_name"])["page_len"]
      .cumsum()
)
df["page_start"] = df["page_end"] - df["page_len"]

AttributeError: 'Series' object has no attribute 'len'

In [15]:
df.columns

Index(['book_id', 'book_category', 'book_type', 'book_date', 'book_name',
       'category_name', 'all_authors', 'main_author_death', 'content',
       'page_count', 'headers', 'header', 'page', 'body', 'headers_tree',
       'page_len', 'page_end', 'page_start'],
      dtype='object')

In [152]:
# Group consecutive rows with same headers
# Convert headers from string → tuple for grouping
# df["headers_tuple"] = df["headers"].apply(lambda x: tuple(eval(x)) if isinstance(x, str) else tuple(x))

# Mark consecutive groups
df["_group"] = (df["headers_tree"] != df["headers_tree"].shift()).cumsum()

# Aggregate
grouped = df.groupby(["_group", "book_id", "headers_tree"], as_index=False).agg(
    book_category=('book_category',list),
    book_type=('book_type',list),
    book_date=('book_date',list),
    book_name=('book_name',list),
    category_name=('category_name',list),
    all_authors=('all_authors',list),
    main_author_death=('main_author_death',list),
    pages=("page", list),
    page_start=('page_start',list),
    page_end=('page_end',list),
    body=("body", lambda texts: " ".join(texts)),
    page_count=("page", "count"),
)

# Drop temp columns from original if desired
df.drop(columns=["_group"], inplace=True)

# Preview
grouped.head()

,_group,book_id,headers_tree,book_category,book_type,book_date,book_name,category_name,all_authors,main_author_death,pages,page_start,page_end,body,page_count
0,1,121,باب القول بالمذهب,"[1, 1]","[1, 1]","[280, 280]",[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني...,"[العقيدة, العقيدة]","[حرب الكرماني, حرب الكرماني]","[280, 280]","[23, 24]","[0, 307]","[307, 622]",# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,2
1,2,121,من زعم أن الإيمان قول بلا عمل,[1],[1],[280],[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني],[العقيدة],[حرب الكرماني],[280],[25],[622],[989],وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,1
2,3,121,من زعم أن الإيمان يزيد ولا ينقص,"[1, 1]","[1, 1]","[280, 280]",[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني...,"[العقيدة, العقيدة]","[حرب الكرماني, حرب الكرماني]","[280, 280]","[26, 27]","[989, 1170]","[1170, 1238]",* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,2
3,4,121,من زعم أن الناس لا يتفاضلون في الإيمان فقد كذب,[1],[1],[280],[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني],[العقيدة],[حرب الكرماني],[280],[28],[1238],[1442],* و# من لم ير الاستثناء في الإيمان \n؛ فهو مرج...,1
4,5,121,القدر خيره وشره من الله,[1],[1],[280],[إجماع السلف في الاعتقاد كما حكاه حرب الكرماني],[العقيدة],[حرب الكرماني],[280],[29],[1442],[1817],* ومن زعم أن المعرفة تنفع (¬١) في القلب وإن لم...,1

In [153]:
grouped['book_type'] = grouped['book_type'].apply(lambda x: x[0])
grouped['book_category'] = grouped['book_category'].apply(lambda x: x[0])
grouped['book_date'] = grouped['book_date'].apply(lambda x: x[0])
grouped['book_name'] = grouped['book_name'].apply(lambda x: x[0])
grouped['category_name'] = grouped['category_name'].apply(lambda x: x[0])
grouped['all_authors'] = grouped['all_authors'].apply(lambda x: x[0])
grouped['main_author_death'] = grouped['main_author_death'].apply(lambda x: x[0])
# grouped['headers_tree'] = grouped['headers_tree'].apply(lambda x: x[0])

In [154]:
grouped.head()

,_group,book_id,headers_tree,book_category,book_type,book_date,book_name,category_name,all_authors,main_author_death,pages,page_start,page_end,body,page_count
0,1,121,باب القول بالمذهب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[23, 24]","[0, 307]","[307, 622]",# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,2
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[25],[622],[989],وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,1
2,3,121,من زعم أن الإيمان يزيد ولا ينقص,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[26, 27]","[989, 1170]","[1170, 1238]",* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,2
3,4,121,من زعم أن الناس لا يتفاضلون في الإيمان فقد كذب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[28],[1238],[1442],* و# من لم ير الاستثناء في الإيمان \n؛ فهو مرج...,1
4,5,121,القدر خيره وشره من الله,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[29],[1442],[1817],* ومن زعم أن المعرفة تنفع (¬١) في القلب وإن لم...,1

In [ ]:
grouped.to_parquet('shameladb_books_enh.parquet')
# !cp -rf shameladb_books_enh.parquet drive/MyDrive/data/shameladb_books_enh.parquet

In [20]:
!du -h shameladb_books_enh.parquet
!du -h shameladb_books_enh.csv

89M	shameladb_books_enh.parquet
du: cannot access 'shameladb_books_enh.csv': No such file or directory

# Chunker

In [ ]:
df = pd.read_parquet('shameladb_books_enh.parquet')
df.head()

,_group,book_id,headers_tree,book_category,book_type,book_date,book_name,category_name,all_authors,main_author_death,pages,page_start,page_end,body,page_count
0,1,121,باب القول بالمذهب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[23, 24]","[0, 307]","[307, 622]",# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,2
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[25],[622],[989],وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,1
2,3,121,من زعم أن الإيمان يزيد ولا ينقص,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[26, 27]","[989, 1170]","[1170, 1238]",* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,2
3,4,121,من زعم أن الناس لا يتفاضلون في الإيمان فقد كذب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[28],[1238],[1442],* و# من لم ير الاستثناء في الإيمان \n؛ فهو مرج...,1
4,5,121,القدر خيره وشره من الله,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[29],[1442],[1817],* ومن زعم أن المعرفة تنفع (¬١) في القلب وإن لم...,1

In [22]:
embed_model = HuggingFaceEmbedding('Omartificial-Intelligence-Space/GATE-AraBert-v1',device='cuda')
splitter = SemanticSplitterNodeParser(
    buffer_size=2, # Contextual buffer (number of sentences) around split points
    breakpoint_percentile_threshold=75, # Sensitivity to semantic shifts
    embed_model=embed_model
)
splitter = SemanticSplitterNodeParser(
    buffer_size=2, # Contextual buffer (number of sentences) around split points
    breakpoint_percentile_threshold=75, # Sensitivity to semantic shifts
    embed_model=embed_model
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/201 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/8.66k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  541MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/2.02k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/761k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.78M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/695 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

In [ ]:
def gen_chunks(text):
    doc = Document(id='1',text=text)
    chunks = splitter([doc])
    return [chunk.text for chunk in chunks]

In [24]:
df['chunks'] = df['body'].progress_apply(gen_chunks)

100%|██████████| 54021/54021 [2:14:01<00:00,  6.72it/s]

In [35]:
df.to_parquet('chunks.parquet')
!cp -rf chunks.parquet drive/MyDrive/data/chunks.parquet

:

:

:

# chunks

In [156]:
# !cp -rf drive/MyDrive/data/chunks.parquet chunks.parquet 
gp = pd.read_parquet('shameladb_books_enh.parquet')
df = pd.read_parquet('chunks.parquet')
# df['chunks'] = df['chunks'].apply(ast.literal_eval)
df.head()

,_group,book_id,headers_tree,book_category,book_type,book_date,book_name,category_name,all_authors,main_author_death,pages,page_start,page_end,body,page_count,chunks
0,1,121,باب القول بالمذهب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[23, 24]","[0, 306]","[306, 620]",# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,2,[# باب القول بالمذهب \n\r* قال أبو القاسم (¬١)...
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[25],[620],[986],وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,1,[وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\...
2,3,121,من زعم أن الإيمان يزيد ولا ينقص,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[26, 27]","[986, 1166]","[1166, 1233]",* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,2,[* ومن زعم أن الإيمان هو القول، والأعمال شرائع...
3,4,121,من زعم أن الناس لا يتفاضلون في الإيمان فقد كذب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[28],[1233],[1436],* و# من لم ير الاستثناء في الإيمان \n؛ فهو مرج...,1,[* و# من لم ير الاستثناء في الإيمان \n؛ فهو مر...
4,5,121,القدر خيره وشره من الله,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[29],[1436],[1810],* ومن زعم أن المعرفة تنفع (¬١) في القلب وإن لم...,1,[* ومن زعم أن المعرفة تنفع (¬١) في القلب وإن ل...

In [158]:
len(grouped),len(df)

(54021, 54021)

In [159]:
df[['pages','page_start','page_end']] = grouped[['pages','page_start','page_end']]

In [160]:
def optimize_int_columns(df):
    optimized_df = df.copy()
    for col in optimized_df.select_dtypes(include=['int64']).columns:
        min_val = optimized_df[col].min()
        max_val = optimized_df[col].max()

        if min_val >= 0:
            if max_val < 255: # uint8
                optimized_df[col] = optimized_df[col].astype('uint8')
            elif max_val < 65535: # uint16
                optimized_df[col] = optimized_df[col].astype('uint16')
            elif max_val < 4294967295: # uint32
                optimized_df[col] = optimized_df[col].astype('uint32')
        else:
            if min_val > -128 and max_val < 127: # int8
                optimized_df[col] = optimized_df[col].astype('int8')
            elif min_val > -32768 and max_val < 32767: # int16
                optimized_df[col] = optimized_df[col].astype('int16')
            elif min_val > -2147483648 and max_val < 2147483647: # int32
                optimized_df[col] = optimized_df[col].astype('int32')
    return optimized_df

# Apply integer optimization
df = optimize_int_columns(df)

In [6]:
# df['pages'] = df['pages'].apply(lambda x: x if pd.isna(x) else ast.literal_eval(x))

In [161]:
df = df.explode('chunks')

In [164]:
ARABIC_RE = r'[\u0600-\u06FF]'

df = df[df["chunks"].str.contains(ARABIC_RE, regex=True, na=False)]

In [165]:
def rel_bounds(ps, pe):
    ends, acc = [], 0
    for s, e in zip(ps, pe):
        acc += e - s      # page length
        ends.append(acc)
        acc += 1          # the join space after each page
    return ends

df['page_end_enh'] = df.apply(lambda r: rel_bounds(r.page_start, r.page_end), axis=1)
df['page_start_enh'] = df['page_end_enh'].apply(lambda e: [0] + e[:-1])

In [208]:
import bisect

def get_pages(row):
    """Page whose text contains the chunk start."""
    start = row.body.find(row.chunks)
    if start == -1:
        return None                      # splitter normalized whitespace; not a verbatim hit
    i = bisect.bisect_right(row.page_end_enh, start)
    return row.pages[i]

df['chunk_page'] = df.progress_apply(get_pages, axis=1)

100%|██████████| 150287/150287 [00:09<00:00, 15686.09it/s]

In [209]:
df.head()

,_group,book_id,headers_tree,book_category,book_type,book_date,book_name,category_name,all_authors,main_author_death,pages,page_start,page_end,body,page_count,chunks,page_end_enh,page_start_enh,chunk_page
0,1,121,باب القول بالمذهب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[23, 24]","[0, 307]","[307, 622]",# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,2,# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,"[307, 623]","[0, 307]",23
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[25],[622],[989],وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,1,وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,[367],[0],25
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,[25],[622],[989],وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,1,* و# من زعم أن الإيمان قول بلا عمل \n؛ فهو مرج...,[367],[0],25
2,3,121,من زعم أن الإيمان يزيد ولا ينقص,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[26, 27]","[989, 1170]","[1170, 1238]",* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,2,* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,"[181, 250]","[0, 181]",26
2,3,121,من زعم أن الإيمان يزيد ولا ينقص,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,280,"[26, 27]","[989, 1170]","[1170, 1238]",* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,2,* [وإن زعم أن الإيمان لا يزيد ولا ينقص فهو مرج...,"[181, 250]","[0, 181]",26

In [212]:
random = np.random.randint(len(df))

# print(df.iloc[random,[1,-6,-4,-3,-2,-1]]['body'])
display(Markdown(df.iloc[random,[1,-6,-4,-3,-2,-1]]['chunks']))
print(str(df.iloc[random,[1,-6,-4,-3,-2,-1]]['book_id']) + '/' + str(df.iloc[random,[1,-6,-4,-3,-2,-1]]['chunk_page']))

## ١٢١ - باب: أفعال العباد مقدرة

20879/780

In [211]:
df.iloc[random,[1,-6,-4,-3,-2,-1]]['chunks'][0]

'ا'

In [20]:
list(df.itertuples())[0]

Pandas(Index=0, _1=1, book_id=121, headers_tree='باب القول بالمذهب', book_category=1, book_type=1, book_date=280, book_name='إجماع السلف في الاعتقاد كما حكاه حرب الكرماني', category_name='العقيدة', all_authors='حرب الكرماني', main_author_death=280, pages=array([23, 24]), page_start=array([  0, 306]), page_end=array([306, 620]), body='# باب القول بالمذهب \n\r* قال أبو القاسم (¬١): حدثنا أبو محمد حرب بن إسماعيل (¬٢) قال (¬٣): هذا مذهب (¬٤) أئمة (¬٥) العلم، وأصحاب الأثر، وأهل السنة [المتمسكين بعروقها] (¬٦) المعروفين (¬٧) بها، المقتدى بهم [فيها] (¬٨)، [من لدن أصحاب النَّبي ﷺ إلى يومنا هذا] (¬٩)، وأدركت مَن أدركت مِن علماء أهل [العراق] (¬١٠) والحجاز والشام وغيرهم [عليها] (¬١)، فمن خالف شيئًا من هذه المذاهب، أو طعن فيها، أو عاب قائلها، فهو [مخالفٌ] (¬٢)، مبتدعٌ، خارجٌ [من] (¬٣) الجماعة، زائل عن منهج السنة وسبيل الحق.\r[قال] (¬٤): [وهو مذهب أحمد (¬٥) وإسحاق بن إبراهيم بن مخلد (¬٦)، وعبد الله بن الزبير الحميدي (¬٧)، وسعيد بن منصور (¬٨)، وغيرهم ممن جالسنا', page_count=2, chunks='# باب القول بالمذهب \n\r* قال أبو القاسم (¬١): حدثنا أبو محمد حرب بن إسماعيل (¬٢) قال (¬٣): هذا مذهب (¬٤) أئمة (¬٥) العلم، وأصحاب الأثر، وأهل السنة [المتمسكين بعروقها] (¬٦) المعروفين (¬٧) بها، المقتدى بهم [فيها] (¬٨)، [من لدن أصحاب النَّبي ﷺ إلى يومنا هذا] (¬٩)، وأدركت مَن أدركت مِن علماء أهل [العراق] (¬١٠) والحجاز والشام وغيرهم [عليها] (¬١)، فمن خالف شيئًا من هذه المذاهب، أو طعن فيها، أو عاب قائلها، فهو [مخالفٌ] (¬٢)، مبتدعٌ، خارجٌ [من] (¬٣) الجماعة، زائل عن منهج السنة وسبيل الحق.\r[قال] (¬٤): [وهو مذهب أحمد (¬٥) وإسحاق بن إبراهيم بن مخلد (¬٦)، وعبد الله بن الزبير الحميدي (¬٧)، وسعيد بن منصور (¬٨)، وغيرهم ممن جالسنا')

In [28]:
get_pages(list(df.itertuples())[1])

Pandas(Index=1, _1=2, book_id=121, headers_tree='من زعم أن الإيمان قول بلا عمل', book_category=1, book_type=1, book_date=280, book_name='إجماع السلف في الاعتقاد كما حكاه حرب الكرماني', category_name='العقيدة', all_authors='حرب الكرماني', main_author_death=280, pages=array([25]), page_start=array([620]), page_end=array([986]), body='وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r*#  الإيمان (¬٣). قول وعمل \n، ونية، وتمسك بالسنة.\r* و# الإيمان يزيد وينقص \n.\r* و# الاستثناء في الإيمان  \nسنة ماضية عن (¬٤) العلماء.\r* [قال] (¬٥): وإذا (¬٦) سُئِل الرجل: أمؤمن أنت؟ فإنه يقول: أنا مؤمن إن شاء الله، أو مؤمن أرجو، أو يقول: آمنت بالله وملائكته وكتبه ورسله.\r* و# من زعم أن الإيمان قول بلا عمل \n؛ فهو مرجئ (¬٧).', page_count=1, chunks='وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r*#  الإيمان (¬٣). قول وعمل \n، ونية، وتمسك بالسنة.\r* و# الإيمان يزيد وينقص \n.\r* و# الاستثناء في الإيمان  \nسنة ماضية عن (¬٤) العلماء.\r* [قال] (¬٥): وإذا (¬٦) سُئِل الرجل: أمؤمن أنت؟ فإنه يقول: أنا مؤمن إن شاء الله، أو مؤمن أرجو، أو يقول: آمنت بالله وملائكته وكتبه ورسله.\r')

In [ ]:
# chunk_pages = []
# for row in df.itertuples():
#     chunk = row.chunks
#     soup = bs(chunk,'html.parser')
#     spans_found = soup.find_all('page')
#     if spans_found:
#         page = spans_found[-1].contents[-1]
#         spans_str = ", ".join([span.contents[0] for span in spans_found])
#         if not spans_str:
#             spans_str = f"{page}, {int(page)+1}"
#     else:
#         spans_str = ", ".join(str(st) for st in row.pages) # Handle cases where no 'page' tags are found
#     chunk_pages.append(spans_str)
# df['chunk_page'] = chunk_pages

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 160733 entries, 0 to 54020
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   _group             160733 non-null  uint16
 1   book_id            160733 non-null  uint32
 2   headers_tree       160733 non-null  object
 3   book_category      160733 non-null  uint8
 4   book_type          160733 non-null  uint8
 5   book_date          160733 non-null  uint32
 6   book_name          160733 non-null  object
 7   category_name      160733 non-null  object
 8   all_authors        160733 non-null  object
 9   main_author_death  160733 non-null  uint32
 10  pages              160733 non-null  object
 11  page_start         160733 non-null  object
 12  page_end           160733 non-null  object
 13  body               160733 non-null  object
 14  page_count         160733 non-null  uint16
 15  chunks             160733 non-null  object
 16  chunk_page         160733 non-null  object
dtypes: object(10), uint16(2), uint32(3), uint8(2)
memory usage: 16.2+ MB

In [13]:
# df['body'] = df['body'].astype(str)
# df['category_name'] = df['category_name'].astype(str)
# df['book_name'] = df['book_name'].astype(str)
# df['headers_tree'] = df['headers_tree'].astype(str)

In [30]:
from camel_tools.utils.charsets import AR_CHARSET

def has_arabic(text):
    return any(ch in AR_CHARSET for ch in text)

df_ = df[df["chunks"].apply(has_arabic)]

In [31]:
df_ = df_.drop(columns=['page_start','page_end','body','page_count','pages'])

In [32]:
def optimize_object_columns(df):
    optimized_df = df.copy()
    for col in tqdm(optimized_df.select_dtypes(include=['object']).columns):
        optimized_df[col] = optimized_df[col].astype('category',errors='ignore')
    return optimized_df

# Apply object optimization
df_ = optimize_object_columns(df_)

100%|██████████| 6/6 [00:01<00:00,  5.20it/s]

In [33]:
df_.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 148411 entries, 0 to 54020
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   _group             148411 non-null  uint16
 1   book_id            148411 non-null  uint32
 2   headers_tree       148411 non-null  category
 3   book_category      148411 non-null  uint8
 4   book_type          148411 non-null  uint8
 5   book_date          148411 non-null  uint32
 6   book_name          148411 non-null  category
 7   category_name      148411 non-null  category
 8   all_authors        148411 non-null  category
 9   main_author_death  148411 non-null  uint32
 10  chunks             148411 non-null  category
 11  chunk_page         148411 non-null  category
dtypes: category(6), uint16(1), uint32(3), uint8(2)
memory usage: 453.2 MB

In [39]:
df_.to_parquet('last.parquet')
!cp -rf chunks.parquet drive/MyDrive/data/last.parquet

In [37]:
from datasets import Dataset
from huggingface_hub import login
dataset = Dataset.from_pandas(df_)

# Push to your repository
dataset.push_to_hub("SHK4K/islam_books",token='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',commit_description='i added books and fixed chunks.')

Uploading the dataset shards:   0%|          | 0/2 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/75 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :  84%|########4 | 51.4MB / 61.0MB

Creating parquet from Arrow format:   0%|          | 0/75 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :  66%|######6   | 20.9MB / 31.6MB

README.md:   0%|          | 0.00/859 [00:00<?, ?B/s]

CommitInfo(commit_url='https://huggingface.co/datasets/SHK4K/islam_books/commit/872a89a5139f51d886ad5871a4cd1ba705fa1b56', commit_message='Upload dataset', commit_description='i added books and fixed chunks.', oid='872a89a5139f51d886ad5871a4cd1ba705fa1b56', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/SHK4K/islam_books', endpoint='https://huggingface.co', repo_type='dataset', repo_id='SHK4K/islam_books'), pr_revision=None, pr_num=None)

In [ ]:
from datasets import Dataset
from huggingface_hub import login

dataset = Dataset.from_pandas(df)

# Push to your repository
dataset.to_parquet('data/full_book')

Creating parquet from Arrow format: 100%|██████████| 8/8 [00:03<00:00,  2.09ba/s]

765856919

Type:        module
String form: <module 'google.colab.runtime' from '/usr/local/lib/python3.12/dist-packages/google/colab/runtime.py'>
File:        /usr/local/lib/python3.12/dist-packages/google/colab/runtime.py
Docstring:   Functionality for working with the Colab runtime.

In [46]:
from google.colab import runtime
runtime.unassign()

# Updates

In [ ]:
from datasets import load_dataset

ds = load_dataset('SHK4K/islam_books')
df = ds['train'].to_pandas()
df.head()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")

README.md:   0%|          | 0.00/886 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/train-00000-of-00002.parquet: reconstructing file:   0%|          |  0.00B / 28.1MB

data/train-00000-of-00002.parquet: downloading bytes:           |  0.00B

data/train-00001-of-00002.parquet: reconstructing file:   0%|          |  0.00B / 20.7MB

data/train-00001-of-00002.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/99771 [00:00<?, ? examples/s]

,_group,book_id,headers_tuple,book_category,book_type,book_date,book_name,category_name,all_authors,pages,page_count,chunks,chunk_page,__index_level_0__
0,1,121,باب القول بالمذهب,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"[23, 24]",2,# باب القول بالمذهب \n\r* قال أبو القاسم (¬١):...,"23, 24",0
1,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,وأخذنا عنهم العلم] (¬١)، فكان من (¬٢) قولهم:\r...,25,1
2,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,* و# من زعم أن الإيمان قول بلا عمل \n؛ فهو مرج...,25,1
3,2,121,من زعم أن الإيمان قول بلا عمل,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,[25],1,<page>25</page>,25,1
4,3,121,من زعم أن الإيمان يزيد ولا ينقص,1,1,280,إجماع السلف في الاعتقاد كما حكاه حرب الكرماني,العقيدة,حرب الكرماني,"[26, 27]",2,* ومن زعم أن الإيمان هو القول، والأعمال شرائع؛...,"26, 27",2

In [ ]:
chunk_pages = []
page = 1
for row in df.itertuples():
    chunk = row.chunks
    soup = bs(chunk,'html.parser')
    spans_found = soup.find_all('page')
    if spans_found:
        page = spans_found[-1].contents[-1]
        spans_str = ", ".join([span.contents[0] for span in spans_found])
        
    else:
        spans_str = f'{page}, {int(page)+1}' # Handle cases where no 'page' tags are found
    chunk_pages.append(spans_str)
df['chunk_page'] = chunk_pages

In [ ]:
from datasets import Dataset
dataset = Dataset.from_pandas(df)

# Push to your repository
dataset.push_to_hub("SHK4K/islam_books",token='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')

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/100 [00:00<?, ?ba/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

                              :  47%|####6     | 22.8MB / 48.5MB

CommitInfo(commit_url='https://huggingface.co/datasets/SHK4K/islam_books/commit/51e5ec615480d34bfbefe7cdf0d30f977d7deffa', commit_message='Upload dataset', commit_description='', oid='51e5ec615480d34bfbefe7cdf0d30f977d7deffa', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/SHK4K/islam_books', endpoint='https://huggingface.co', repo_type='dataset', repo_id='SHK4K/islam_books'), pr_revision=None, pr_num=None)