In [13]:
import pandas as pd

df = pd.read_csv('data/full_hadith.csv')
df.head()

/tmp/ipykernel_1260942/3029587273.py:3: DtypeWarning: Columns (0: Al-Albani, 1: Muhammad Muhyi Al-Din Abdul Hamid, 2: Shuaib Al Arnaut, 3: Zubair Ali Zai, 4: source, 5: comments, 6: Muhammad Fouad Abd al-Baqi, 7: Salim al-Hilali, 8: Abu Ghuddah, 9: Ahmad Muhammad Shakir, 10: Bashar Awad Maarouf) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/full_hadith.csv')

,Unnamed: 0,bookname,hadithnumber,arabicnumber,text,Al-Albani,Muhammad Muhyi Al-Din Abdul Hamid,Shuaib Al Arnaut,Zubair Ali Zai,book,...,comments,link,linkmin,Muhammad Fouad Abd al-Baqi,Salim al-Hilali,Abu Ghuddah,Ahmad Muhammad Shakir,Bashar Awad Maarouf,sanad,matn
0,0,Sunan Abu Dawud,1.0,1.0,حدثنا عبد الله بن مسلمة بن قعنب القعنبي، حدثنا...,Hasan Sahih,Hasan Sahih,Sahih Lighairihi,Isnaad Hasan,abudawud,...,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN,NaN,NaN,NaN,حدثنا عبد الله بن مسلمة بن قعنب القعنبي ، حدثن...,، أن النبي صلى الله عليه وسلم كان إذا ذهب المذ...
1,1,Sunan Abu Dawud,2.0,2.0,حدثنا مسدد بن مسرهد، حدثنا عيسى بن يونس، أخبرن...,Sahih,Sahih,Sahih Lighairihi,Daif,abudawud,...,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN,NaN,NaN,NaN,حدثنا مسدد بن مسرهد ، حدثنا عيسى بن يونس ، أخب...,الله أن النبي صلى الله عليه وسلم كان إذا أراد ...
2,2,Sunan Abu Dawud,3.0,3.0,حدثنا موسى بن إسماعيل، حدثنا حماد، أخبرنا أبو ...,Daif,Daif,Daif,Daif,abudawud,...,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN,NaN,NaN,NaN,حدثنا موسى بن إسماعيل ، حدثنا حماد ، أخبرنا أب...,قدم عبد الله بن عباس البصرة فكان يحدث عن أبي م...
3,3,Sunan Abu Dawud,4.0,4.0,حدثنا مسدد بن مسرهد، حدثنا حماد بن زيد، وعبد ا...,Sahih,Sahih,Sahih,Sahih Bukhari (142) Sahih Muslim (375),abudawud,...,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN,NaN,NaN,NaN,حدثنا مسدد بن مسرهد ، حدثنا حماد بن زيد ، وعبد...,كان رسول الله صلى الله عليه وسلم إذا دخل الخلا...
4,4,Sunan Abu Dawud,5.0,5.0,حدثنا الحسن بن عمرو، - يعني السدوسي - حدثنا وك...,Shadh,Shadh,NaN,Isnaad Sahih,abudawud,...,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN,NaN,NaN,NaN,حدثنا الحسن بن عمرو ، - يعني السدوسي - حدثنا و...,"، بهذا الحديث قال "" اللهم إني أعوذ بك "". وقال ..."

In [14]:
def fix_df(df_):
    df_ = df_[df_['language'].isin(['Arabic'])]
    df_ = df_[df_['name'].isin([
    'ara-abudawud',
    'ara-bukhari',
    'ara-dehlawi',
    'ara-ibnmajah',
    'ara-malik',
    'ara-muslim',
    'ara-nasai',
    'ara-nawawi',
    'ara-qudsi',
    'ara-tirmidhi'])]
    df_ = df_.reset_index(drop=True)
    df_ = df_.drop(columns=[
    'author',
    'direction',
    'source',
    'language',
    'has_sections',
    'Muhammad Muhyi Al-Din Abdul Hamid',
    'Shuaib Al Arnaut',
    'Zubair Ali Zai',
    'Muhammad Fouad Abd al-Baqi',
    'Salim al-Hilali',
    'Abu Ghuddah',
    'Ahmad Muhammad Shakir',
    'Bashar Awad Maarouf',])
    return df_

df = fix_df(df)

In [15]:
df[df['book']=='muslim']

,Unnamed: 0,bookname,hadithnumber,arabicnumber,text,Al-Albani,book,hadith,section,name,comments,link,linkmin,sanad,matn
19104,155912,Sahih Muslim,1.0,NaN,NaN,NaN,muslim,1,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN
19105,155913,Sahih Muslim,2.0,NaN,NaN,NaN,muslim,2,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN
19106,155914,Sahih Muslim,3.0,NaN,وحدثني زهير بن حرب، حدثنا إسماعيل، - يعني ابن ...,NaN,muslim,3,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,وحدثني زهير بن حرب ، حدثنا إسماعيل ، - يعني اب...,قال إنه ليمنعني أن أحدثكم حديثا كثيرا أن رسول ...
19107,155915,Sahih Muslim,4.0,NaN,وحدثنا محمد بن عبيد الغبري، حدثنا أبو عوانة، ع...,NaN,muslim,4,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,وحدثنا محمد بن عبيد الغبري ، حدثنا أبو عوانة ،...,"قال رسول الله صلى الله عليه وسلم "" من كذب على ..."
19108,155916,Sahih Muslim,5.0,NaN,NaN,NaN,muslim,5,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26662,163470,Sahih Muslim,7559.0,3032.01,حدثنا أبو بكر بن أبي شيبة، حدثنا علي بن مسهر، ...,NaN,muslim,36,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,حدثنا أبو بكر بن أبي شيبة ، حدثنا علي بن مسهر ...,قال خطب عمر على منبر رسول الله صلى الله عليه و...
26663,163471,Sahih Muslim,7560.0,3032.02,وحدثنا أبو كريب، أخبرنا ابن إدريس، حدثنا أبو ح...,NaN,muslim,37,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,وحدثنا أبو كريب ، أخبرنا ابن إدريس ، حدثنا أبو...,الخطاب ، على منبر رسول الله صلى الله عليه وسلم...
26664,163472,Sahih Muslim,7561.0,3032.03,وحدثنا أبو بكر بن أبي شيبة، حدثنا إسماعيل ابن ...,NaN,muslim,38,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,وحدثنا أبو بكر بن أبي شيبة ، حدثنا إسماعيل ابن...,، بهذا الإسناد. بمثل حديثهما غير أن ابن علية ف...
26665,163473,Sahih Muslim,7562.0,3033.01,حدثنا عمرو بن زرارة، حدثنا هشيم، عن أبي هاشم، ...,NaN,muslim,39,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,حدثنا عمرو بن زرارة ، حدثنا هشيم ، عن أبي هاشم...,، يقسم قسما إن { هذان خصمان اختصموا في ربهم } ...
26666,163474,Sahih Muslim,7563.0,3033.02,حدثنا أبو بكر بن أبي شيبة، حدثنا وكيع، ح وحدثن...,NaN,muslim,40,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,حدثنا أبو بكر بن أبي شيبة ، حدثنا وكيع ، ح وحد...,ذر ، يقسم لنزلت { هذان خصمان } بمثل حديث هشيم.

In [8]:
import pandas as pd

# df = pd.read_parquet('hf://datasets/SHK4K/hadith/data/train-00000-of-00001.parquet')
df2 = pd.read_parquet("hf://datasets/fawazahmed0/hadith-data/data/train-00000-of-00001-ada9a2a41dc08d71.parquet")

In [9]:
df2_clean = fix_df(df2)

In [10]:
df2_clean[df2_clean['book']=='muslim']

,bookname,hadithnumber,arabicnumber,text,Al-Albani,book,hadith,section,name,comments,link,linkmin
19104,Sahih Muslim,1.0,NaN,,NaN,muslim,1,Introduction,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...
19105,Sahih Muslim,2.0,NaN,,NaN,muslim,2,Introduction,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...
19106,Sahih Muslim,3.0,NaN,وَحَدَّثَنِي زُهَيْرُ بْنُ حَرْبٍ، حَدَّثَنَا ...,NaN,muslim,3,Introduction,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...
19107,Sahih Muslim,4.0,NaN,وَحَدَّثَنَا مُحَمَّدُ بْنُ عُبَيْدٍ الْغُبَرِ...,NaN,muslim,4,Introduction,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...
19108,Sahih Muslim,5.0,NaN,,NaN,muslim,5,Introduction,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...
...,...,...,...,...,...,...,...,...,...,...,...,...
26662,Sahih Muslim,7559.0,3032.01,حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ، ح...,NaN,muslim,36,The Book of Commentary on the Qur'an,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...
26663,Sahih Muslim,7560.0,3032.02,وَحَدَّثَنَا أَبُو كُرَيْبٍ، أَخْبَرَنَا ابْنُ...,NaN,muslim,37,The Book of Commentary on the Qur'an,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...
26664,Sahih Muslim,7561.0,3032.03,وَحَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ،...,NaN,muslim,38,The Book of Commentary on the Qur'an,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...
26665,Sahih Muslim,7562.0,3033.01,حَدَّثَنَا عَمْرُو بْنُ زُرَارَةَ، حَدَّثَنَا ...,NaN,muslim,39,The Book of Commentary on the Qur'an,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...
26666,Sahih Muslim,7563.0,3033.02,حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ، ح...,NaN,muslim,40,The Book of Commentary on the Qur'an,ara-muslim,,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...

In [16]:
df['text'] = df2_clean['text']

In [17]:
df[df['book']=='muslim']

,Unnamed: 0,bookname,hadithnumber,arabicnumber,text,Al-Albani,book,hadith,section,name,comments,link,linkmin,sanad,matn
19104,155912,Sahih Muslim,1.0,NaN,,NaN,muslim,1,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN
19105,155913,Sahih Muslim,2.0,NaN,,NaN,muslim,2,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN
19106,155914,Sahih Muslim,3.0,NaN,وَحَدَّثَنِي زُهَيْرُ بْنُ حَرْبٍ، حَدَّثَنَا ...,NaN,muslim,3,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,وحدثني زهير بن حرب ، حدثنا إسماعيل ، - يعني اب...,قال إنه ليمنعني أن أحدثكم حديثا كثيرا أن رسول ...
19107,155915,Sahih Muslim,4.0,NaN,وَحَدَّثَنَا مُحَمَّدُ بْنُ عُبَيْدٍ الْغُبَرِ...,NaN,muslim,4,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,وحدثنا محمد بن عبيد الغبري ، حدثنا أبو عوانة ،...,"قال رسول الله صلى الله عليه وسلم "" من كذب على ..."
19108,155916,Sahih Muslim,5.0,NaN,,NaN,muslim,5,Introduction,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26662,163470,Sahih Muslim,7559.0,3032.01,حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ، ح...,NaN,muslim,36,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,حدثنا أبو بكر بن أبي شيبة ، حدثنا علي بن مسهر ...,قال خطب عمر على منبر رسول الله صلى الله عليه و...
26663,163471,Sahih Muslim,7560.0,3032.02,وَحَدَّثَنَا أَبُو كُرَيْبٍ، أَخْبَرَنَا ابْنُ...,NaN,muslim,37,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,وحدثنا أبو كريب ، أخبرنا ابن إدريس ، حدثنا أبو...,الخطاب ، على منبر رسول الله صلى الله عليه وسلم...
26664,163472,Sahih Muslim,7561.0,3032.03,وَحَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ،...,NaN,muslim,38,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,وحدثنا أبو بكر بن أبي شيبة ، حدثنا إسماعيل ابن...,، بهذا الإسناد. بمثل حديثهما غير أن ابن علية ف...
26665,163473,Sahih Muslim,7562.0,3033.01,حَدَّثَنَا عَمْرُو بْنُ زُرَارَةَ، حَدَّثَنَا ...,NaN,muslim,39,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,حدثنا عمرو بن زرارة ، حدثنا هشيم ، عن أبي هاشم...,، يقسم قسما إن { هذان خصمان اختصموا في ربهم } ...
26666,163474,Sahih Muslim,7563.0,3033.02,حَدَّثَنَا أَبُو بَكْرِ بْنُ أَبِي شَيْبَةَ، ح...,NaN,muslim,40,The Book of Commentary on the Qur'an,ara-muslim,NaN,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,https://cdn.jsdelivr.net/gh/fawazahmed0/hadith...,حدثنا أبو بكر بن أبي شيبة ، حدثنا وكيع ، ح وحد...,ذر ، يقسم لنزلت { هذان خصمان } بمثل حديث هشيم.

In [18]:
import os
from datasets import Dataset

ds = Dataset.from_pandas(df)
ds.push_to_hub(repo_id='SHK4K/hadith',token=os.environ["HF_TOKEN"])

Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
Creating parquet from Arrow format: 100%|██████████| 1/1 [00:00<00:00,  3.18ba/s]
Processing Files (1 / 1): 100%|██████████| 21.4MB / 21.4MB, 73.2kB/s
New Data Upload: 100%|██████████| 11.4MB / 11.4MB, 73.0kB/s
Uploading the dataset shards: 100%|██████████| 1/1 [01:58<00:00, 118.34s/ shards]

CommitInfo(commit_url='https://huggingface.co/datasets/SHK4K/hadith/commit/60e8271505bb1221e320ff55f83971fdf19da55f', commit_message='Upload dataset', commit_description='', oid='60e8271505bb1221e320ff55f83971fdf19da55f', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/SHK4K/hadith', endpoint='https://huggingface.co', repo_type='dataset', repo_id='SHK4K/hadith'), pr_revision=None, pr_num=None)

In [1]:
import torch
embs = torch.load('tensors/hadith.pt')

In [3]:
len(embs)

28949